### ISSUE TITLE
add translated subs

### ISSUE THREAD

**Issue by Joe12-24** [sdaqo/mpv-subs-popout#2]
I would like to add translated subtitles, such as bilingual or trilingual subtitles. Hello, I would like to ask if it is possible to integrate ChatGPT for translation.

**Comment by sdaqo** [comment]
I do not exactly know what you mean. Do you mean that you want to have multiple subtitle tracks showing at once with some of them being translated by some external translation tool?

**Comment by Joe12-24** [comment]
> I do not exactly know what you mean. Do you mean that you want to have multiple subtitle tracks showing at once with some of them being translated by some external translation tool?

![image](https://github.com/sdaqo/mpv-subs-popout/assets/46116540/12968de8-dad8-48cf-93d5-ca90994a2dd4)
yep！Like this.

**Comment by Joe12-24** [comment]
I'd like to ask, how much time did it take you to write that? I've been learning Rust recently, and after finishing the basics, I'm unsure of what I can do. I don't have a specific goal in mind. Are you a full-time Rust developer?

**Comment by sdaqo** [comment]
> 
> ![image](https://user-images.githubusercontent.com/46116540/253881552-12968de8-dad8-48cf-93d5-ca90994a2dd4.png) yep！Like this.
 
I do not know how feasible this is because we can only  translate the subs as they are coming in and this takes time (making the web request etc.) thus the translated subs will show later then the actual subs. It would make more sense to translate the subs beforehand. I will try tho and see how it goes. 

Another thing similar to this that I also want to make is integrating a dictionary. Basically you click on a word (or hover. idk yet) and it pops up a dictionary entry of that word under your cursor. This kind of approach could also be used for translating, and would be a nice feature for language learning.

**Comment by sdaqo** [comment]
> I'd like to ask, how much time did it take you to write that? I've been learning Rust recently, and after finishing the basics, I'm unsure of what I can do. I don't have a specific goal in mind. Are you a full-time Rust developer?

Not to much, the project is relatively small. The thing that consumed the most time was porting it to windows.

As for your other question: I am not a Rust developer and also just recently started using it. Rust is just a programming language, and like a lot of programming languages you can do pretty much anything in it. Try coming up with some project you want to do, be that automating something in your daily life, making some stupid and useless stuff just for fun, a game or some other stuff that seems interesting. Just learning the language (syntax, control flow, etc.) does not really help, you have to start **using** the whole ecosystem of the language (libraries, other projects, etc.) to really get familiar with it  and the best way to do that is to write your own projects.

**Comment by Joe12-24** [comment]
> > ![image](https://user-images.githubusercontent.com/46116540/253881552-12968de8-dad8-48cf-93d5-ca90994a2dd4.png) yep！Like this.
> 
> I do not know how feasible this is because we can only translate the subs as they are coming in and this takes time (making the web request etc.) thus the translated subs will show later then the actual subs. It would make more sense to translate the subs beforehand. I will try tho and see how it goes.
> 
> Another thing similar to this that I also want to make is integrating a dictionary. Basically you click on a word (or hover. idk yet) and it pops up a dictionary entry of that word under your cursor. This kind of approach could also be used for translating, and would be a nice feature for language learning.

![image](https://github.com/sdaqo/mpv-subs-popout/assets/46116540/0df143c0-5562-46bf-905c-81082b79c877)
Just like this, it is also a good idea to select English words and translate words or sentences.

**Comment by Joe12-24** [comment]
> > I'd like to ask, how much time did it take you to write that? I've been learning Rust recently, and after finishing the basics, I'm unsure of what I can do. I don't have a specific goal in mind. Are you a full-time Rust developer?
> 
> Not to much, the project is relatively small. The thing that consumed the most time was porting it to windows.
> 
> As for your other question: I am not a Rust developer and also just recently started using it. Rust is just a programming language, and like a lot of programming languages you can do pretty much anything in it. Try coming up with some project you want to do, be that automating something in your daily life, making some stupid and useless stuff just for fun, a game or some other stuff that seems interesting. Just learning the language (syntax, control flow, etc.) does not really help, you have to start **using** the whole ecosystem of the language (libraries, other projects, etc.) to really get familiar with it and the best way to do that is to write your own projects.
Wow, you totally get what I mean!
Yes, you are right,  Just learning the language (syntax, control flow, etc.) does not really help, I forget it after a while, and I don’t even remember that I have learned this programming language，Thank you very much, I am  Chinese, my English is relatively poor, I use Google Translate, lol...

**Comment by Joe12-24** [comment]
Hi, My Chinese name is Gaoju, and my English name is Alex, I am 29 years old. My job is a java developer or including some front-end（like vue.js） . I am glad to meet you, and thank you very much for your patient answer !

**Comment by sdaqo** [comment]
> ![image](https://user-images.githubusercontent.com/46116540/253990516-0df143c0-5562-46bf-905c-81082b79c877.png) Just like this, it is also a good idea to select English words and translate words or sentences.

Yup, will try to implement this. Putting it on the TODO List.

**Comment by sdaqo** [comment]
https://github.com/sdaqo/mpv-subs-popout/assets/63876564/363c39be-fb05-4ea0-b0ec-8a7b3bd5b7f4

So, this is my first prototype, it works quite well, better then I expected. I would have expected that the delay would impact the watching experience more. I do not know how accurate the translations are tho as I don't know any Chinese, it is using Google Translate. This is of course not what the end result is gonna look like, but I think, looking at this, that your Idea with the multiple subs is also feasible! So I will try implementing your Idea and mine.

**Comment by Joe12-24** [comment]
It’s so great！ your execution is really strong, and you made a demo so quickly, that’s probably what it means. Later, you can also package it into a browser plug-in. Is your implementation logic to extract screen text? Does it support dual subtitles like when  watch on the Netflix or YouTube? I see that plug-ins like this on the Internet are charged. I think you can also complete it, fighting~

**Comment by sdaqo** [comment]
@Joe12-24  Now then, I am done. Please look into it and tell me what you think! Open for feedback.
