### ISSUE TITLE
[FR] add text wrapping

### ISSUE THREAD

**Issue by zkvsky** [sdaqo/mpv-subs-popout#4]
I have subs with some really long lines, and the widget grows beyond the screen in such cases. I'd love to limit its size, lock it and wrap the text instead.

**Comment by sdaqo** [comment]
Yeah good idea, I will look into it!

**Comment by sdaqo** [comment]
Ok you can now tick a checkbox to lock the current size and wrap the text, note that only the minimum size is locked so you can still expand the window (this is a limitation of gtk3 the gui framework), it should still work perfecly fine. I will release the new as soon as the build is finished, please try it and tell me if that works for you.

**Comment by sdaqo** [comment]
https://github.com/sdaqo/mpv-subs-popout/releases/tag/v0.4.1

**Comment by zkvsky** [comment]
Work's great, that's exactly what I wanted. I would add some padding on the left and right of the window though [so the text doesn't touch the sides].
I'm under Plasma so neither -docked nor -no-border work, no that it matters to me, but it might be worth noting in the docs. Thanks!

**Comment by sdaqo** [comment]
> Work's great, that's exactly what I wanted. I would add some padding on the left and right of the window though [so the text doesn't touch the sides]. 

Alright

> I'm under Plasma so neither -docked nor -no-border work, no that it matters to me, but it might be worth noting in the docs. Thanks!

Those do not work under wayland (the window server you are probably running) unfortunately and there is nothing to do about it as these properties can not be controlled by the applications themselves on wayland.

**Comment by sdaqo** [comment]
https://github.com/sdaqo/mpv-subs-popout/releases/tag/v0.4.2

**Comment by zkvsky** [comment]
> > Work's great, that's exactly what I wanted. I would add some padding on the left and right of the window though [so the text doesn't touch the sides].
> 
> Alright
> 
> > I'm under Plasma so neither -docked nor -no-border work, no that it matters to me, but it might be worth noting in the docs. Thanks!
> 
> Those do not work under wayland (the window server you are probably running) unfortunately and there is nothing to do about it as these properties can not be controlled by the applications themselves on wayland.

Oh, gotcha, not an issue for me, but maybe consider alternative toolkit somewhere down the line?

**Comment by sdaqo** [comment]
I don't really plan for it, no. While yes, gtk3 is 1. kinda deprecated (because gtk4 exists) and 2. A little finicky to work with, switching over will not solve those problems because the toolkit can't really do anything about it. There probably are workarounds but those only work on certain window managers/compositors. One thing you can do tho is changing these properties manually, I think you can right click (there is also a shortcut, I don't remember) on the window bar at the top and set all these settings by yourself.

**Comment by zkvsky** [comment]
> I don't really plan for it, no. While yes, gtk3 is 1. kinda deprecated (because gtk4 exists) and 2. A little finicky to work with, switching over will not solve those problems because the toolkit can't really do anything about it. There probably are workarounds but those only work on certain window managers/compositors. One thing you can do tho is changing these properties manually, I think you can right click (there is also a shortcut, I don't remember) on the window bar at the top and set all these settings by yourself.

Yeah, as I said, it's not a big issue since I can do all of this via window manager's options [on-top, remove borders]
