### ISSUE TITLE
Can you add DeepLX

### ISSUE THREAD

**Issue by ghost** [sdaqo/mpv-subs-popout#5]
DeepL is the best translator tbf, https://github.com/OwO-Network/DeepLX with this we can have free api, also if you gonna add this pls let user define their [endpoint](https://deeplx.owo.network/endpoints/pro.html)

**Comment by sdaqo** [comment]
I am going to look into it.

Edit: I have to do some stuff before this, so this may take a bit.

**Comment by ghost** [comment]
Okay thanks!

**Comment by sdaqo** [comment]
Allright, this is done now. I will release the new version soon.  The endpoint can be defined by changing the url in the ui, if you are using the /v2/translate endpoint you have to set the api key to `[yourAccessToken] [yourAuthKey]` (with space), I did not test this as I do not have a deepl pro account, but it should work.

**Comment by ghost** [comment]
@sdaqo thank you but i set it to http://localhost:1188/v1/translate (it does not need api key too) but it does not remember it and turns back to http://localhost:1188/translate, there is 3 endpoint i guess you forgot the add /v1/ one

**Comment by sdaqo** [comment]
you are right, this is fixed now, thanks

**Comment by ghost** [comment]
@sdaqo tested everything works very fine, thank you so much creating this beauty!
